apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: demo
  namespace: vault-demo
spec:
  vaultConnectionRef: vault
  namespace: demo
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: demo-app
    serviceAccount: demo-app
    audiences:
      - vault
    tokenExpirationSeconds: 3600
